name: Update Links

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get links
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/SCRIPTS/link-updater.cjs')
            await script({core, fetch})

      - name: Commit readme modifications
        uses: stefanzweifel/git-auto-commit-action@v4
        id: get-links
        with:
          file_pattern: 'README.md'
          commit_message: 'Update links'

      - name: Updated
        if: steps.get-links.outputs.changes_detected == true
        run: echo "Updated"

      - name: Not updated
        if: steps.get-links.outputs.changes_detected == false
        run: echo "Not updated"
