name: Update Books

on:
  schedule:
  - cron: '0 12 * * *'
    
  
  workflow_dispatch:

jobs:
  books:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get books
        uses: actions/github-script@v6
        id: get-book
        with:
          github-token: 1
          script: |
            const script = require('./.github/SCRIPTS/book-updater.cjs')
            await script({core, fetch})
      
          
      - if: ${{ steps.get-book.outputs.changed == true }}
        uses: sarisia/actions-commit@master
        
