name: Update Recipes

on:
  schedule:
    - cron: '*/60 * * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: 'https://recetas.eduardoparra.es/rss.xml'
          file: 'README.md'
          format: '- [${title}](${url})'
          start_flag: '<!-- START_SECTION:recipes -->'
          end_flag: '<!-- END_SECTION:recipes -->'
          

      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 1
      # - uses: actions/setup-node@v4
      #   with:
      #     cache: 'npm'
      #     node-version-file: '.nvmrc'

      # - name: Install dependencies
      #   run: npm ci --ignore-scripts

      # - name: Update recipes
      #   run: npm run update-readme
          
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
